{
 "title": "AirPurifier",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current PM 2.5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "air_purifier_pm25", "legendFormat": "PM 2.5" }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "air_purifier_temp_celsius", "legendFormat": "Temp" }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "air_purifier_humidity_percent", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "PM 2.5 Concentration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    { "expr": "air_purifier_pm25", "legendFormat": "PM 2.5" }
   ]
  },
  {
   "title": "Room temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "air_purifier_temp_celsius", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "air_purifier_humidity_percent", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Filter life percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "air_purifier_filter_life_percent",
     "legendFormat": "Filter life percent"
    }
   ]
  },
  {
   "title": "Motor speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "air_purifier_motor_speed", "legendFormat": "Motor speed" }
   ]
  }
 ]
}