{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(crt_weather_temperature[2h])) by (city)",
     "legendFormat": "{{city}} - Temp"
    },
    {
     "expr": "avg(avg_over_time(crt_weather_apparentTemperature[2h])) by (city)",
     "legendFormat": "{{city}} - ApparentTemp"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "hPa" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(crt_weather_pressure[2h]))",
     "legendFormat": "{{city}} - pressure"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(crt_weather_windSpeed[2h]))",
     "legendFormat": "{{city}} - WindSpeed"
    },
    {
     "expr": "avg(avg_over_time(crt_weather_windGust[2h]))",
     "legendFormat": "{{city}} - WindGust"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(crt_weather_humidity[2h]) * 100)",
     "legendFormat": "{{city}} - Humidity"
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(crt_weather_cloudCover[2h]) * 100)",
     "legendFormat": "{{city}} - Cloud Cover"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(crt_weather_precipProbability) * 100",
     "legendFormat": "{{city}} - Probability of precipitation"
    },
    {
     "expr": "avg(crt_weather_precipIntensity)",
     "legendFormat": "{{city}} - precipIntensity"
    }
   ]
  },
  {
   "title": "Daily Mean Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(crt_weather_temperature[1d])) by (city)",
     "legendFormat": "{{city}} - Temp"
    },
    {
     "expr": "avg(avg_over_time(crt_weather_apparentTemperature[1d])) by (city)",
     "legendFormat": "{{city}} - ApparentTemp"
    }
   ]
  }
 ]
}